spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: status
          uri: lb://STATUS-SERVICE
          predicates:
            - Path=/status/**
          filters:
            - StripPrefix=1

        - id: veiculos
          uri: lb://CATALOGO-VEICULOS-SERVICE
          predicates:
            - Path=/veiculos/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
  instance:
    instance-id: ${spring.application.name}:${random.value}

server:
  port: 8089