name: CI for Status Service

on:
  push:
    branches:
      - mai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Configurar Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Compilar e Testar
        run: |
          cd status-service # navegue até o diretório do serviço
          ./mvnw clean verify # ou 'mvn clean verify' se não usar o wrapper

      - name: Informar sucesso
        run: echo "Compilação e testes do status-service concluídos com sucesso!"
