name: Deploy to Kubernetes

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code from k8s branch
        uses: actions/checkout@v4
        with:
          ref: k8s

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Give execution permission to mvnw
        run: chmod +x status-service/mvnw

      - name: Build with Maven
        run: |
          cd status-service # Navigate to the service directory
          ./mvnw clean verify # or 'mvn clean verify' if not using the wrapper

      - name: Build Docker image
        run: |
          docker build -t status-service:latest ./status-service

      - name: Install KinD
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.16.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/

      - name: Create KinD cluster
        run: kind create cluster

      - name: Load Docker image into KinD
        run: |
          kind load docker-image status-service:latest

      - name: Deploy to KinD Kubernetes
        run: |
          kubectl apply -f k8s/status.yml


